name: First pipeline CICD

on:
  push: 
    branches: 
      -main

jobs:
  build: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up React
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          npm-version: '9'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      